### PR TITLE
Convert to Maven-project

### PR DESCRIPTION
**Pull request by Androkai**
Adding pom.xml and restructure project-files

### CODE REVIEW

**Comment by blablubbabc** [comment]
Hm, I was thinking about converting it to a gradle project as I just started using gradle for most of my other projects.

**Comment by Androkai** [comment]
It's up to you to decide. :wink: I only want to use it with Jenkins for automatic building.

**Comment by blablubbabc** [comment]
Okay, I will close this pull request. Check out the latest changes: I converted it to a gradle project.
By the way, it is still building against bukkit 1.9 because there are no requirements or breaking changes in 1.10 which affect AntiXRay.
And future releases of AntiXRay will be compiled with java 8 now.

**Comment by Androkai** [comment]
Thx a lot.

**Comment by Androkai** [comment]
When building this is generated: build/libs/workspace-1.8.6.jar
Is it possible to rename it to something like AntiXRay-1.8.6.jar or maybe I did something wrong and you know what? Sorry, it's my first time working with Gradle.

**Comment by blablubbabc** [comment]
It seems that I missed to push a gradle related file to the repository. Check if it works now.

**Comment by Androkai** [comment]
[Works](https://jenkins.androkai.net/job/AntiXRay/10/), thx! ^^

**Pull request closed without merging**
